version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data

#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.15.0
#    container_name: kibana
#    depends_on:
#      - elasticsearch
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - "5601:5601"
  #  db:
  #    image: postgres:13
  #    volumes:
  #      - postgres_data:/var/lib/postgresql/data
  #    environment:
  #      POSTGRES_USER: postgres
  #      POSTGRES_PASSWORD: password
  #      POSTGRES_DB: myapp_development

  api:
    build: api
    ports:
      - "8081:8081"

#  web:
#    build: ./web
#    command: bash -c "rm -f /myapp/tmp/pids/server.pid &&  bin/rails db:create db:migrate && rails server -b 0.0.0.0"
#    volumes:
#      - ./web:/myapp
#    ports:
#      - "3000:3000"
#    environment:
#      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
#    depends_on:
#      - db

volumes:
  postgres_data:
  es-data:
    driver: local