version: '3.8'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"